# -*- coding: utf-8 -*-
"""Biomecânica código fonte 3/3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oJgxjn616jKKFs4o2sYIGqDfCd6KyI2v
"""

# Commented out IPython magic to ensure Python compatibility.
# Instala o Matplotlib (>=3.4.0) e a extensão ipympl para gráficos interativos em Jupyter Notebooks.
!pip install matplotlib>=3.4.0
!pip install ipympl

# Use %matplotlib inline to set the backend before importing ipympl
# %matplotlib inline

# Now import ipympl
import ipympl

# from google.colab import drive
# drive.mount('/content/drive')

# Habilita o gerenciamento de widgets personalizados e importa bibliotecas necessárias.

from google.colab import output
output.enable_custom_widget_manager()
from google.colab import files
import pandas as pd
import io

# Define a função CriaVetorDados que converte uma lista de strings com números em floats, substituindo vírgulas por pontos.
def CriaVetorDados(vetor):
  if type(vetor[0]) == str:
    n = [vetor[i].replace(',', '.') for i in range(len(vetor))]
    n = [float(i) for i in n]
    return n
  else:
    n = vetor
    return n

# Importa bibliotecas necessárias: re para expressões regulares, pandas para manipulação de dados, numpy para operações numéricas, e matplotlib para visualização e animação.
from re import M
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.animation as animation

# Definir o caminho do arquivo
file_path = 'trajetoria_ajustada (m).csv'

# Carregar o arquivo
arquivo = pd.read_csv(file_path, sep=',')  # Especifica o separador
print(arquivo.head())
t = CriaVetorDados(arquivo["Time"])

M1X = CriaVetorDados(arquivo["Marcador 1/0/X"])
M1Y = CriaVetorDados(arquivo["Marcador 1/0/Y"])
M2X = CriaVetorDados(arquivo["Marcador 2/0/X"])
M2Y = CriaVetorDados(arquivo["Marcador 2/0/Y"])
M3X = CriaVetorDados(arquivo["Marcador 3/0/X"])
M3Y = CriaVetorDados(arquivo["Marcador 3/0/Y"])
M4X = CriaVetorDados(arquivo["Marcador 4/0/X"])
M4Y = CriaVetorDados(arquivo["Marcador 4/0/Y"])


marcadoresY = [M1Y, M2Y, M3Y, M4Y]
marcadoresX = [M1X, M2X, M3X, M4X]


#usar M1X e M1Y como referência
def Normalizar(marcadoresX, marcadoresY):
  referenciaX = np.array(marcadoresX[0])
  referenciaY = np.array(marcadoresY[0])
  for i in range(len(marcadoresX)):
    marcadoresX[i] = np.array(marcadoresX[i]) - referenciaX
    marcadoresY[i] = np.array(marcadoresY[i]) - referenciaY
  return marcadoresX, marcadoresY

marcadoresX, marcadoresY = Normalizar(marcadoresX, marcadoresY)


M1X = marcadoresX[0]
M1Y = marcadoresY[0]
M2X = marcadoresX[1]
M2Y = marcadoresY[1]
M3X = marcadoresX[2]
M3Y = marcadoresY[2]
M4X = marcadoresX[3]
M4Y = marcadoresY[3]

# from google.colab import drive
# drive.mount('/content/drive')

"""# Nova seção"""

#  tamanho da figura
plt.figure(figsize=(10, 6))

#Plota sem o tempo
plt.clf()
plt.plot(M1X, M1Y, 'ro', label="marcador da mão")
plt.plot(M2X, M2Y, 'bo', label="marcador da cotovelo")
plt.plot(M3X, M3Y, 'go', label="marcador do ombro")
plt.plot(M4X, M4Y, 'yo', label="marcador do tronco")



plt.xlabel('Posição X')
plt.ylabel('Posição Y')
plt.title('Gráfico de Posição X ao Longo do Tempo')
plt.legend()
plt.grid(True)
plt.show()
type(t[0])

# Define a função Velocidade que calcula a velocidade em 2D a partir de coordenadas X e Y e um vetor de tempos t, retornando a magnitude da velocidade.

def Velocidade(X, Y, t):
    # Inicializar listas para armazenar velocidades e acelerações
    VX = np.zeros(len(X))
    VY = np.zeros(len(Y))
    A = np.zeros(len(X))

    # Calcular a velocidade
    for i in range(len(X) - 1):
        VX[i] = (X[i + 1] - X[i]) / (t[i + 1] - t[i])  # Velocidade em X
        VY[i] = (Y[i + 1] - Y[i]) / (t[i + 1] - t[i])  # Velocidade em Y

    velocidade = np.sqrt(np.power(VX, 2) + np.power(VY, 2))
    angle = np.arctan2(VY, VX)
    # Calcular a aceleração
    for i in range(len(VX) - 1):
        A[i] =  (velocidade[i + 1] - velocidade[i]) / (t[i + 1] - t[i])  # Aceleração em X

    return velocidade, A, angle

V1, A1, ang1 = Velocidade(M1X, M1Y, t)
V2, A2, ang2 = Velocidade(M2X, M2Y, t)
V3, A3, ang3 = Velocidade(M3X, M3Y, t)
V4, A4, ang4 = Velocidade(M4X, M4Y, t)
velocidades = [V1, V2, V3, V4]
Aceleracoes = [A1, A2, A3, A4]

plt.clf()
plt.plot(t, A1, 'r')
plt.plot(t, A2, 'g')
plt.plot(t, A3, 'b')
plt.plot(t, A4, 'y')
plt.xlabel('Tempo')
plt.ylabel('Aceleração')
plt.title('Gráfico da Aceleração no Tempo - Não Filtrada')
plt.legend()
plt.grid(True)
plt.show()

# Limpa a figura atual e plota as velocidades de três conjuntos de dados (M1, M2 e M3) ao longo do tempo, com uma grade e rótulos para os eixos.
plt.clf()
plt.plot(t, V1, 'r', label="marcador da mão")
plt.plot(t, V2, 'b', label="marcador da cotovelo")
plt.plot(t, V3, 'g', label="marcador do ombro")
plt.plot(t, V4, 'y', label="marcador do tronco")

plt.grid(True)
plt.ylabel('Velocidade')
plt.xlabel('Tempo')
plt.title('Gráfico da Velocidade no Tempo - Não Filtrado')
plt.legend()
plt.show()
plt.show()

# Importa funções do scipy para filtragem
from scipy.signal import butter, filtfilt
from IPython.display import clear_output

clear_output(wait=True)

# Exemplo de dados: velocidade ao longo do tempo
fs = 30  # taxa de amostragem (Hz)
cutoff = 2  # frequência de corte em Hz


# Função para criar o filtro
def butter_lowpass_filter(data, cutoff, fs, order=2):
    nyquist = 0.5 * fs
    normal_cutoff = cutoff / nyquist
    b, a = butter(order, normal_cutoff, btype='low', analog=False)
    y = filtfilt(b, a, data)
    return y


# Aplicar o filtro na velocidade
velocidade_filtrada1 = butter_lowpass_filter(V1, cutoff, fs)
velocidade_filtrada2 = butter_lowpass_filter(V2, cutoff, fs)
velocidade_filtrada3 = butter_lowpass_filter(V3, cutoff, fs)
velocidade_filtrada4 = butter_lowpass_filter(V4, cutoff, fs)

# Aplicar o filtro na aceleração
Aceleracoes_filtradas1 = butter_lowpass_filter(A1, cutoff, fs)
Aceleracoes_filtradas2 = butter_lowpass_filter(A2, cutoff, fs)
Aceleracoes_filtradas3 = butter_lowpass_filter(A3, cutoff, fs)
Aceleracoes_filtradas4 = butter_lowpass_filter(A4, cutoff, fs)


#Aplicar o filtro no angulo

Angulo_filtrado1 = butter_lowpass_filter(ang1, cutoff, fs)
Angulo_filtrado2 = butter_lowpass_filter(ang2, cutoff, fs)
Angulo_filtrado3 = butter_lowpass_filter(ang3, cutoff, fs)
Angulo_filtrado4 = butter_lowpass_filter(ang4, cutoff, fs)

plt.clf()
plt.figure(figsize=(10, 6))
plt.plot(t, velocidade_filtrada1, 'r', label = 'marcador do punho')
plt.plot(t, velocidade_filtrada2, 'g', label = 'marcador da cotovelo')
plt.plot(t, velocidade_filtrada3, 'b', label = 'marcador do ombro')
plt.plot(t, velocidade_filtrada4, 'y', label = 'marcador do tronco')
plt.grid(True)
plt.ylabel('Velocidade')
plt.xlabel('Tempo')
plt.title('Gráfico da Velocidade no Tempo - Filtrado')
plt.legend()
plt.show()

# Plotagem do sinal filtrado ao longo do tempo, com grade e rótulos.
plt.clf()
plt.plot(t, Aceleracoes_filtradas1, 'r', label = 'marcador do punho')
plt.plot(t, Aceleracoes_filtradas2, 'g', label = 'marcador do cotovelo')
plt.plot(t, Aceleracoes_filtradas3, 'b', label = 'marcador do ombro')
plt.plot(t, Aceleracoes_filtradas4, 'y', label = 'marcador do tronco')
plt.grid(True)
plt.ylabel('Aceleração')
plt.xlabel('Tempo')
plt.title('Gráfico da Aceleração no Tempo - Filtrado')
plt.legend()
plt.show()

import matplotlib.pyplot as plt
import numpy as np
import matplotlib.animation as animation

plt.clf()
#Configuração inicial do gráfico
fig, ax = plt.subplots()
line1, = ax.plot([], [], label='Marcador do punho', color = 'red')
line2, = ax.plot([], [], label='Marcador do cotovelo', color = 'green')
line3, = ax.plot([], [], label='Marcador do ombro', color = 'blue')
line4, = ax.plot([], [], label='Marcador do tronco', color = 'yellow')

ax.set_xlim(np.min(t), np.max(t))  # Define os limites do eixo X
ax.set_ylim(np.min(velocidades) , np.max(velocidades))  # Define os limites do eixo Y
ax.set_xlabel('Tempo')
ax.set_ylabel('Velocidade')
ax.legend()

# # Função para inicializar o gráfico
def init():
  line1.set_data([], [])
  line2.set_data([], [])
  line3.set_data([], [])
  line4.set_data([], [])
  return line1, line2, line3, line4,

# # Função de animação para atualizar os dados
def animate(i):
  line1.set_data(t[:i], velocidade_filtrada1[:i])  # Atualiza os dados do gráfico
  line2.set_data(t[:i], velocidade_filtrada2[:i])  # Atualiza os dados do gráfico
  line3.set_data(t[:i], velocidade_filtrada3[:i])  # Atualiza os dados do gráfico
  line4.set_data(t[:i], velocidade_filtrada4[:i])  # Atualiza os dados do gráfico
  return line1, line2, line3, line4,

# # Criação da animação
ani = animation.FuncAnimation(fig, animate, init_func=init, frames=len(t), interval=50, blit=True)
ani.save('velocidade.mp4', writer='ffmpeg', fps=30)
# # Exibir o gráfico animado
plt.show()

import numpy as np
import matplotlib.pyplot as plt
from matplotlib.animation import FuncAnimation

# Suponha que você tenha dois arrays: um para ângulos e outro para magnitudes
# Exemplos de dados

angles1 = ang1  # Ângulos
magnitudes1 = velocidade_filtrada1 #velocidade
angles2 = Angulo_filtrado2  # Ângulos
magnitudes2 = velocidade_filtrada2 #velocidade
angles3 = Angulo_filtrado3  # Ângulos
magnitudes3 = velocidade_filtrada3 #velocidade
angles4 = Angulo_filtrado4  # Ângulos
magnitudes4 = velocidade_filtrada4 #velocidade

magnitudes = np.concatenate((magnitudes2, magnitudes3, magnitudes4))
angles = np.concatenate((angles2, angles3, angles4))

# Configurações do gráfico polar
fig, ax = plt.subplots(subplot_kw={'projection': 'polar'})
ax.set_ylim(0, np.max(magnitudes))  # Limite do raio (magnitude)

# Vetor inicial
line1, = ax.plot([], [], lw=3,color='red')
line2, = ax.plot([], [], lw=3,color='green')
line3, = ax.plot([], [], lw=3,color='blue')
line4, = ax.plot([], [], lw=3,color='yellow')

point1, = ax.plot([], [], 'ro')  # Criar o ponto vermelho no gráfico
point2, = ax.plot([], [], 'go')  # Criar o ponto verde no gráfico
point3, = ax.plot([], [], 'bo')  # Criar o ponto azul no gráfico
point4, = ax.plot([], [], 'yo')  # Criar o ponto amarelo no gráfico


# Função para iniciar o gráfico
def init():
    line1.set_data([], [])
    line2.set_data([], [])
    line3.set_data([], [])
    line4.set_data([], [])
    point1.set_data([], [])
    point2.set_data([], [])
    point3.set_data([], [])
    point4.set_data([], [])

    return line1, line2, line3, line4, point1, point2, point3, point4,

# Função para atualizar o gráfico em cada frame
def update(frame):
    angle1 = angles1[frame]  # Ângulo correspondente ao frame
    angle2 = angles2[frame]  # Ângulo correspondente ao frame
    angle3 = angles3[frame]  # Ângulo correspondente ao frame
    angle4 = angles4[frame]  # Ângulo correspondente ao frame
    f1 = magnitudes1[frame]  # Magnitude correspondente ao frame
    f2 = magnitudes2[frame]  # Magnitude correspondente ao frame
    f3 = magnitudes3[frame]  # Magnitude correspondente ao frame
    f4 = magnitudes4[frame]  # Magnitude correspondente ao frame

    # Definindo as coordenadas polares (ângulo e magnitude)
    x1= [angle1, angle1]  # Ângulo atualizado
    y1 = [0, f1]  # Magnitude atualizada

    x2= [angle2, angle2]  # Ângulo atualizado
    y2 = [0, f2]  # Magnitude atualizada

    x3= [angle3, angle3]  # Ângulo atualizado
    y3 = [0, f3]  # Magnitude atualizada

    x4= [angle4, angle4]  # Ângulo atualizado
    y4 = [0, f4]  # Magnitude atual

    line1.set_data(x1, y1)
    point1.set_data(angle1, f1)
    line2.set_data(x2, y2)
    point2.set_data(angle2, f2)
    line3.set_data(x3, y3)
    point3.set_data(angle3, f3)
    line4.set_data(x4, y4)
    point4.set_data(angle4, f4)


    return line1, line2, line3, line4, point1, point2, point3, point4,

# Cria a animação
ani = FuncAnimation(fig, update, frames=len(angles1), init_func=init, blit=True)

# Salva a animação em um arquivo .mp4
ani.save('animated_vector_with_data.mp4', writer='ffmpeg', fps=30)

plt.show()

def VelocidadeAngular(An, t):
    # Inicializar listas para armazenar velocidades e acelerações
    V = np.zeros(len(An))
    A = np.zeros(len(An))

    # Calcular a velocidade
    for i in range(len(An) - 1):
        V[i] = (An[i + 1] - An[i]) / (t[i + 1] - t[i])  # Velocidade Angular

    for i in range(len(V) - 1):
        A[i] =  (V[i + 1] - V[i]) / (t[i + 1] - t[i])  # Aceleração em X

    return V, A

def interpolate_on_line(x1, y1, x2, y2, percentage):
    """Calcula o ponto em uma linha baseado em uma porcentagem do comprimento."""
    x = x1 + percentage * (x2 - x1)
    y = y1 + percentage * (y2 - y1)
    return x, y

def calculate_length(x1, y1, x2, y2):
    """Calcula o comprimento entre dois pontos (x1, y1) e (x2, y2)."""
    return np.sqrt((x2 - x1)**2 + (y2 - y1)**2)

def calculate_angle(x1, y1, x2, y2, x3, y3):

    # Vetores dos segmentos
    AB = np.array([x2 - x1, y2 - y1])
    BC = np.array([x3 - x2, y3 - y2])

    # Produto escalar e magnitudes
    dot_product = np.dot(AB, BC)
    magnitude_AB = np.linalg.norm(AB)
    magnitude_BC = np.linalg.norm(BC)

    # Cálculo do ângulo em radianos
    angle_rad = np.arccos(dot_product / (magnitude_AB * magnitude_BC))

    # Converte para graus
    angle_deg = np.degrees(angle_rad)


        # Vetores das duas linhas
    v1 = np.array([x1 - x2, y1 - y2])
    v2 = np.array([x3 - x2, y3 - y2])

    # Ângulo entre as linhas
    angle_rad = np.arccos(np.dot(v1, v2) / (np.linalg.norm(v1) * np.linalg.norm(v2)))
    angle = np.degrees(angle_rad)  # Converter para graus

    return angle_deg

# Função para desenhar arco entre duas linhas
from matplotlib import animation
from matplotlib.patches import Arc

def draw_arc(x1, y1, x2, y2, x3, y3, Mycolor, ajuste, textoX,textoY):
    # Vetores das duas linhas
    v1 = np.array([x1 - x2, y1 - y2])
    v2 = np.array([x3 - x2, y3 - y2])

    # Ângulo entre as linhas
    angle_rad = np.arccos(np.dot(v1, v2) / (np.linalg.norm(v1) * np.linalg.norm(v2)))
    angle = np.degrees(angle_rad)  # Converter para graus

    # Desenhando arco entre as duas linhas
    raio = 0.05  # Raio do arco

    # Arco espelhado para a esquerda
    arc_left = Arc([x2, y2], 2 * raio, 2 * raio, angle = ajuste, theta1=180 - angle, theta2=180, color=Mycolor)
    ax.add_patch(arc_left)

    # Adicionando o texto do ângulo
    mid_x = (x2 + x3) / 2 + textoX
    mid_y = (y2 + y3) / 2 + textoY
    ax.text(mid_x, mid_y, f'{angle:.1f}°', fontsize=10, ha='center', color=Mycolor)

# Função para remover arcos antigos
def clear_arcs():
    for patch in ax.patches:
        patch.remove()
    for text in ax.texts:  # Remove textos antigos
        text.remove()

def calculate_line_length(x1, y1, x2, y2):
    """
    Calcula o comprimento da linha entre dois pontos.
    Args:
        x1, y1: Coordenadas do ponto inicial.
        x2, y2: Coordenadas do ponto final.
    Returns:
        float: Comprimento da linha.
    """
    return np.sqrt((x2 - x1)**2 + (y2 - y1)**2)

# Função para calcular o vetor unitário da direção da linha
def direction_vector(x1, y1, x2, y2):
    dx = x2 - x1
    dy = y2 - y1
    magnitude = (dx**2 + dy**2)**0.5
    return dx / magnitude, dy / magnitude  # Retorna o vetor unitário

#from google.colab import drive
#drive.mount('/content/drive')

import math
import pandas as pd

def calcular_terceiro_lado(lado1, lado2, angulo_em_graus):
  angulo_em_radianos = math.radians(angulo_em_graus)
  lado3 = math.sqrt(lado1**2 + lado2**2 - 2 * lado1 * lado2 * math.cos(angulo_em_graus))
  return lado3

# Configuração inicial do gráfico
fig, ax = plt.subplots()
fig.patch.set_alpha(0.5)
point, = ax.plot([], [], alpha=0.3)


BracoAlavancaTriceps = []
BracoAlavancaBiceps = []
Biceps = []
Triceps = []
AnguloCotovelo = []
AnguloAntebraco = []
AnguloOmbro = []

length_line1 = []
length_line2 = []
length_line3 = []

ax.set_xlim(-0.400, 0.600)  # Define os limites do eixo X
ax.set_ylim(-0.900, 0.100)  # Define os limites do eixo Y

point1, = ax.plot([], [], 'ro')  # Ponto vermelho
point2, = ax.plot([], [], 'go')  # Ponto verde
point3, = ax.plot([], [], 'bo')  # Ponto azul
point4, = ax.plot([], [], 'yo')  # Ponto amarelo
point5, = ax.plot([], [], 'o', color='purple')  # Ponto roxo

line1, = ax.plot([], [], 'blue')  # Linha azul
line2, = ax.plot([], [], 'purple')  # Linha roxa
line3, = ax.plot([], [], 'red')  # Linha vermelha
line4, = ax.plot([], [], 'green')  # Linha verde


line_green, = ax.plot([], [], color='green', linestyle='--', linewidth=1.5)  # Linha verde adicional
line_blue_green, = ax.plot([], [], color='purple', linestyle='--', linewidth=1.5)  # Linha roxa entre verde e azul
line_red_green, = ax.plot([], [], color='orange', linestyle='--', linewidth=1.5)  # Linha laranja entre vermelho e verde


# Criação dos pontos para as origens e inserções dos músculos
# point_muscle_green_start, = ax.plot([], [], 'go', label='Origem músculo verde')  # Ponto de origem da linha verde
# point_muscle_green_end, = ax.plot([], [], 'ro', label='Inserção músculo verde')  # Ponto de inserção da linha verde
# point_muscle_orange_start, = ax.plot([], [], 'mo', label='Origem músculo laranja')  # Ponto de origem da linha laranja
# point_muscle_orange_end, = ax.plot([], [], 'co', label='Inserção músculo laranja')  # Ponto de inserção da linha laranja


ax.set_xlabel('Posição X')
ax.set_ylabel('Posição Y')
ax.legend()

# Função auxiliar para interpolar o ponto na linha
def interpolate_on_line(x1, y1, x2, y2, percentage):
    """Calcula o ponto em uma linha baseado em uma porcentagem do comprimento."""
    x = x1 + percentage * (x2 - x1)
    y = y1 + percentage * (y2 - y1)
    return x, y

# Parâmetros de porcentagem para os pontos das linhas
percentage_start_blue = 0.01  # 23% do comprimento da reta azul
percentage_end_green = 0.01  # 1% do comprimento da reta verde
percentage_start_green = 0.99  # 25% do comprimento da reta verde (para a linha azul)
percentage_start_red = 0.90   # 75% do comprimento da reta vermelha (para a linha verde)


# Função para inicializar o gráfico
def init():
    point1.set_data([], [])
    point2.set_data([], [])
    point3.set_data([], [])
    point4.set_data([], [])
    point5.set_data([], [])
    line1.set_data([], [])
    line2.set_data([], [])
    line3.set_data([], [])
    line_green.set_data([], [])
    line_blue_green.set_data([], [])
    line_red_green.set_data([], [])
    # point_muscle_green_start.set_data([], [])
    # point_muscle_green_end.set_data([], [])
    # point_muscle_orange_start.set_data([], [])
    # point_muscle_orange_end.set_data([], [])
    return (
        point1, point2, point3, point4, point5, line1, line2, line3, line4,
        line_green, line_blue_green, line_red_green
    )


# Função para atualizar os dados do gráfico a cada quadro
def animate(i):

    # point1.set_data(M1X[i], M1Y[i])
    # point2.set_data(M2X[i], M2Y[i])
    # point3.set_data(M3X[i], M3Y[i])
    # point4.set_data(M4X[i], M4Y[i])
    # point5.set_data(M2X[i],M1Y[i])



    # Calculando a direção da linha azul
    dir_x, dir_y = direction_vector(M1X[i], M1Y[i], M2X[i], M2Y[i])

    # Prolongando a linha azul 0.05 unidades além do ponto final
    extension = 0.05  # Valor da extensão
    extended_x = M2X[i] + dir_x * extension
    extended_y = M2Y[i] + dir_y * extension

    # Linha azul original
    line1.set_data([M1X[i], M2X[i]], [M1Y[i], M2Y[i]])

    # Linha azul projetada além do ponto final
    line2.set_data([M2X[i], extended_x], [M2Y[i], extended_y])

    # Outras linhas e objetos do gráfico
    line3.set_data([M3X[i], M4X[i]], [M3Y[i], M4Y[i]])

    # Projeção de outras linhas, arcos, etc.
    line4.set_data([M3X[i], M2X[i]], [M3Y[i], M2Y[i]])
    # # Calculando a direção da linha azul
    # dir_x, dir_y = direction_vector(M1X[i], M1Y[i], M2X[i], M2Y[i])

    # # Prolongando a linha azul 0.05 unidades além do ponto final
    # extension = 0.05  # Valor da extensão
    # extended_x = M2X[i] + dir_x * extension
    # extended_y = M2Y[i] + dir_y * extension

    # # Linha azul original
    # line1.set_data([M1X[i], M2X[i]], [M1Y[i], M2Y[i]])

    # # Linha azul projetada além do ponto final
    # line2.set_data([M2X[i], extended_x], [M2Y[i], extended_y])

    # # Outras linhas e objetos do gráfico
    # line3.set_data([M3X[i], M4X[i]], [M3Y[i], M4Y[i]])

    # # Projeção de outras linhas, arcos, etc.

    # Ponto inicial da linha verde na reta azul
    start_x, start_y = interpolate_on_line(M3X[i], M3Y[i], M4X[i], M4Y[i], percentage_start_blue)

    # Ponto final da linha verde na reta verde
    end_x, end_y = interpolate_on_line(M2X[i], M2Y[i], M3X[i], M3Y[i], percentage_end_green)

    # Atualizar a linha verde
    line_green.set_data([start_x, extended_x], [start_y, extended_y])

    start_x_blue, start_y_blue = interpolate_on_line(M2X[i], M2Y[i], M3X[i], M3Y[i], percentage_start_green)

    # Adicionar nova linha laranja entre a linha vermelha e a linha verde
    start_x_red, start_y_red = interpolate_on_line(M1X[i], M1Y[i], M2X[i], M2Y[i], percentage_start_red)
    line_red_green.set_data([start_x_red, start_x_blue], [start_y_red, start_y_blue])

    # Remover arcos antigos
    clear_arcs()

    # Desenhando arcos
    draw_arc(M2X[i], M2Y[i], M3X[i], M3Y[i], M4X[i], M4Y[i], 'blue', 50, -0.05, 0.05)
    draw_arc(M1X[i], M1Y[i], M2X[i], M2Y[i], M3X[i], M3Y[i], 'tomato', -95, 0.05, 0.1)

    # Atualizar os pontos de origem e inserção
    origemTriceps = [start_x, start_y]#começo da linha verde projetada (verde)
    insercaoTriceps = [extended_x, extended_y]  # Final da linha verde projetada (vermelho)
    OrigemBiceps = [start_x_red, start_y_red] #Começo da linha laranja projetada (magenta)
    insercaoBiceps = [start_x_blue, start_y_blue ]#Final da linha laranja projetada(azul)

     # Calcular comprimentos das retas em tempo real
    length_green = calculate_length(start_x, start_y, end_x, end_y)
    length_blue_green = calculate_length(start_x_blue, start_y_blue, M3X[i], M3Y[i])
    length_red_green = calculate_length(start_x_red, start_y_red, start_x_blue, start_y_blue)
    BracoAlavancaTriceps.append(calculate_length(M2X[i], M2Y[i], extended_x , extended_y))
    BracoAlavancaBiceps.append(calculate_length(M1X[i], M1Y[i], M2X[i], M2Y[i]))

    # Cálculo dos comprimentos das linhas no quadro i
    length_line1.append(calculate_line_length(M1X[i], M1Y[i], M2X[i], M2Y[i]))
    length_line2.append(calculate_line_length(M3X[i], M3Y[i], M2X[i], M2Y[i]))
    length_line3.append(calculate_line_length(M3X[i], M3Y[i], M4X[i], M4Y[i]))

    #comprimentos médios dos ossos
    CompAzul = np.mean(length_line1)
    CompVerde = np.mean(length_line2)
    CompVermelho = np.mean(length_line3)

    #calcula o tamanho dos músculos

    Biceps.append(calculate_line_length(start_x, start_y, extended_x, extended_y))
    Triceps.append(calculate_line_length(start_x_red, start_y_red, start_x_blue, start_y_blue))
    AnguloCotovelo.append(calculate_angle(M1X[i], M1Y[i], M2X[i], M2Y[i], M3X[i], M3Y[i]))
    AnguloAntebraco.append(calculate_angle(M2X[i], M1Y[i], M2X[i], M2Y[i], M3X[i], M3Y[i]))
    AnguloOmbro.append(calculate_angle(M2X[i], M2Y[i], M3X[i], M3Y[i], M4X[i], M4Y[i]))


    #Biceps.append(length_green)
    #Triceps.append(length_red_green)

    #Plotandoos o tamanho do musculo
    # ax.text(M1X[i]+ 0.2, M1Y[i], f'{length_green:.5f}', fontsize=10, ha='center', color='orange')
    # ax.text(M1X[i]+ 0.2, M1Y[i]-0.1, f'{length_red_green:.5f}', fontsize=10, ha='center', color='green')


    return (
        point1, point2, point3, point4, point5, line1, line2, line3, line4,
        line_green, line_blue_green, line_red_green
    )

# Criação da animação
ani = animation.FuncAnimation(fig, animate, init_func=init, frames=len(t), interval=1/30, blit=True)
ani.save('animacao.mp4', writer='ffmpeg', fps=30)

# Exibir o gráfico animado
plt.show()

# import pandas as pd


# # Criação do DataFrame
# df = pd.DataFrame({
#     "Tempo (s)": t,
#     "Origem Tríceps (x, y)": origemTriceps,
#     "Inserção Tríceps (x, y)": insercaoTriceps,
#     "Origem Bíceps (x, y)": OrigemBiceps,
#     "Inserção Bíceps (x, y)": insercaoBiceps
# })

# # Salvar como arquivo CSV
# df.to_csv("coordenadas_musculos.csv", index=False)

# print("Arquivo CSV criado com sucesso!")

CompAzul = np.mean(length_line1)
CompVerde = np.mean(length_line2)
CompVermelho = np.mean(length_line3)

print(CompAzul)
print(np.mean(length_line2))
print(np.mean(length_line3))

BicepsTruncado = Biceps[:len(t)]
TricepsTruncado = Triceps[:len(t)]
BicepsTruncado = butter_lowpass_filter(BicepsTruncado, cutoff, fs)
TricepsTruncado = butter_lowpass_filter(TricepsTruncado, cutoff, fs)



plt.clf()
plt.figure(figsize=(10, 6))
plt.plot(t, BicepsTruncado, 'orange', label = 'Bíceps')
plt.plot(t, TricepsTruncado, 'green', label = 'Tríceps')

plt.grid(True)
plt.ylabel('Comprimento do musculo')
plt.xlabel('Tempo')
#plt.title('Gráfico da Velocidade no Tempo - Filtrado')
plt.legend()
plt.show()

print(len(Biceps))

BicepsTruncado = Biceps[:len(t)]
TricepsTruncado = Triceps[:len(t)]
print(len(BicepsTruncado))

plt.clf()
plt.figure(figsize=(10, 6))
plt.plot(AnguloCotovelo, Biceps[:len(AnguloCotovelo)], 'orange', label = 'comprimento do Bíceps')
plt.plot(AnguloCotovelo, Triceps[:len(AnguloCotovelo)], 'green', label = 'comprimento do Tríceps')

plt.grid(True)
plt.ylabel('Comprimento dos musculo')
plt.xlabel('ângulo do cotovelo')
#plt.title('Gráfico da Velocidade no Tempo - Filtrado')
plt.legend()
plt.show()

# Importa funções do scipy para filtragem
from scipy.signal import butter, filtfilt
from IPython.display import clear_output

clear_output(wait=True)

VA1, AA1 = VelocidadeAngular(AnguloCotovelo[:len(t)], t)
VA2, AA2 = VelocidadeAngular(AnguloOmbro[:len(t)], t)

VA1 = butter_lowpass_filter(VA1, cutoff, fs)
VA2 = butter_lowpass_filter(VA2, cutoff, fs)
AA1 = butter_lowpass_filter(AA1, cutoff, fs)
AA2 = butter_lowpass_filter(AA2, cutoff, fs)

plt.clf()
plt.figure(figsize=(10, 6))
plt.plot(t, VA1, 'r', label = 'Marcador do cotovelo')
plt.plot(t, VA2, 'g', label = 'Marcador do ombro')

plt.grid(True)
plt.ylabel('Velocidade')
plt.xlabel('Tempo')
plt.title('Gráfico da Velocidade angular')
plt.legend()
plt.show()

plt.clf()
plt.figure(figsize=(10, 6))
plt.plot(t, AA1[:len(t)], 'r', label = 'Marcador do cotovelo')
plt.plot(t, AA2[:len(t)], 'g', label = 'Marcador do ombro')


plt.grid(True)
plt.ylabel('Aceleração')
plt.xlabel('Tempo')
plt.title('Gráfico da Aceleração angular')
plt.legend()
plt.show()

def VelocidadeM(X, t):
    # Inicializar listas para armazenar velocidades e acelerações
    VM = np.zeros(len(X))
    A = np.zeros(len(X))

    # Calcular a velocidade
    for i in range(len(X) - 1):
        VM[i] = (X[i + 1] - X[i]) / (t[i + 1] - t[i])  # Velocidade em X

    # Calcular a aceleração
    for i in range(len(VM) - 1):
        A[i] =  (VM[i + 1] - VM[i]) / (t[i + 1] - t[i])  # Aceleração em X

    return VM, A

VelocidadeBiceps, AceleracaoBiceps = VelocidadeM(BicepsTruncado, t)
VelocidadeTriceps, AceleracaoTriceps = VelocidadeM(TricepsTruncado, t)
VelocidadeBiceps = butter_lowpass_filter(VelocidadeBiceps, cutoff, fs)
VelocidadeTriceps = butter_lowpass_filter(VelocidadeTriceps, cutoff, fs)
AceleracaoBiceps = butter_lowpass_filter(AceleracaoBiceps, cutoff, fs)
AceleracaoTriceps = butter_lowpass_filter(AceleracaoTriceps, cutoff, fs)


plt.clf()
plt.figure(figsize=(10, 6))
plt.plot(t, VelocidadeBiceps[:len(t)],  'green', label = 'Bíceps')
plt.plot(t, VelocidadeTriceps[:len(t)], 'orange', label = 'Tríceps')

plt.grid(True)
plt.ylabel('Variação do cumprimento')
plt.xlabel('Tempo')
plt.title('Gráfico da Velocidade muscular')
plt.legend()
plt.show()

plt.clf()
plt.figure(figsize=(10, 6))
plt.plot(t[20:], AceleracaoBiceps[20:len(t)],  'green', label = 'Bíceps')
plt.plot(t[20:], AceleracaoTriceps[20:len(t)], 'orange', label = 'Tríceps')


plt.grid(True)
plt.ylabel('Aceleração')
plt.xlabel('Tempo')
plt.title('Gráfico da Aceleração muscular')
plt.legend()
plt.show()

"""#Terceira Parte do Projeto"""

import pandas as pd
import numpy as np

#Definição das Variáveis

Peso = 70 #Peso do indivíduo em kilos
Altura = 1.76 #Altura em metros

#Definindo função que calcula o momento de inércia
def CalculaMomentoInercia(ProporcaoMassa, ProporcaoComprimento, ProporcaoRaiodeGiro):
  massa = 70 * ProporcaoMassa
  Comprimento = 1.76 * ProporcaoComprimento
  RaiodeGiro = Comprimento * ProporcaoRaiodeGiro

  return  ((RaiodeGiro**2) * massa)

# Dados dos segmentos
segmentos = [
    {"Nome": "Tronco", "ProporcaoMassa": 0.416, "ProporcaoComprimento": 0.33, "ProporcaoRaiodeGiro": 0.496},
    {"Nome": "Braço", "ProporcaoMassa": 0.028, "ProporcaoComprimento": 0.186, "ProporcaoRaiodeGiro": 0.436},
    {"Nome": "Antebraço", "ProporcaoMassa": 0.016, "ProporcaoComprimento": 0.146, "ProporcaoRaiodeGiro": 0.430},
]

# Calculando os momentos de inércia
tabela_resultados = []
for segmento in segmentos:
    momento = CalculaMomentoInercia(
        segmento["ProporcaoMassa"],
        segmento["ProporcaoComprimento"],
        segmento["ProporcaoRaiodeGiro"]
    )
    tabela_resultados.append({"Segmento": segmento["Nome"], "Momento de Inércia (kg·m²)": momento})

# Exibindo a tabela
import pandas as pd

df = pd.DataFrame(tabela_resultados)
print(df)

def CalculaTorque(massa_segmento, comprimento_segmento, raio_giro, aceleracao_angular, angulo_articular, massa_corpo=0, distancia_centro_massa_corpo=0):
    """
    Calcula o torque em uma articulação baseado em componentes gravitacionais e inerciais.

    Parâmetros:
    - massa_segmento (float): Massa do segmento em kg (ex.: braço ou antebraço).
    - comprimento_segmento (float): Comprimento do segmento em metros.
    - raio_giro (float): Raio de giro do segmento (proporção do comprimento que define a distribuição de massa).
    - aceleracao_angular (float): Aceleração angular do segmento em rad/s².
    - angulo_articular (float): Ângulo da articulação (em radianos), usado para calcular forças gravitacionais.
    - massa_corpo (float): Massa adicional do corpo em kg (para considerar o peso do corpo suspenso). Default: 0.
    - distancia_centro_massa_corpo (float): Distância do centro de massa do corpo até a articulação, em metros. Default: 0.

    Retorno:
    - torque (float): Torque total na articulação, em N·m.
    """
    # Constante da gravidade
    g = 9.81  # m/s²

    # Momento de inércia do segmento
    momento_inercia = massa_segmento * (raio_giro * comprimento_segmento) ** 2

    # Componente inercial (resistência ao movimento rotacional)
    torque_inercial = momento_inercia * aceleracao_angular

    # Componente gravitacional do segmento
    forca_gravitacional_segmento = massa_segmento * g
    torque_gravitacional_segmento = forca_gravitacional_segmento * (comprimento_segmento / 2) * abs(math.sin(angulo_articular))

    # Componente gravitacional do corpo (se aplicável)
    torque_gravitacional_corpo = massa_corpo * g * distancia_centro_massa_corpo * abs(math.sin(angulo_articular))

    # Torque total
    torque_total = torque_inercial + torque_gravitacional_segmento + torque_gravitacional_corpo

    return torque_total

print(len(AA1))

import numpy as np
import matplotlib.pyplot as plt

# Parâmetros dos segmentos e do corpo
massa_braco = 3.0  # kg (massa do braço)
comprimento_braco = 0.35  # m (comprimento do braço)
raio_giro_braco = 0.45  # proporção do comprimento

massa_antebraco = 2.5  # kg (massa do antebraço)
comprimento_antebraco = 0.30  # m (comprimento do antebraço)
raio_giro_antebraco = 0.4  # proporção do comprimento

massa_corpo = 70.0  # kg (massa total do corpo)
distancia_centro_massa_corpo = 0.55  # m (distância do centro de massa ao ombro)
g = 9.81  # aceleração gravitacional (m/s²)

# Função para calcular o torque
def CalculaTorque(massa_segmento, comprimento_segmento, raio_giro, aceleracao_angular, angulo_articular, massa_corpo=0, distancia_centro_massa_corpo=0):
    raio_giro_m = comprimento_segmento * raio_giro
    momento_inercia = massa_segmento * raio_giro_m**2
    componente_inercial = momento_inercia * aceleracao_angular
    componente_gravitacional = massa_corpo * g * distancia_centro_massa_corpo * np.cos(angulo_articular)
    return componente_inercial + componente_gravitacional

# Calcular o torque no ombro
torque_ombro = CalculaTorque(
    massa_segmento=massa_braco,
    comprimento_segmento=comprimento_braco,
    raio_giro=raio_giro_braco,
    aceleracao_angular=AA1,
    angulo_articular=AnguloOmbro[:len(t)],
    massa_corpo=massa_corpo,
    distancia_centro_massa_corpo=distancia_centro_massa_corpo
)

# Calcular o torque no cotovelo
torque_cotovelo = CalculaTorque(
    massa_segmento=massa_antebraco,
    comprimento_segmento=comprimento_antebraco,
    raio_giro=raio_giro_antebraco,
    aceleracao_angular=AA2,
    angulo_articular= AnguloCotovelo[:len(t)]
)

# Plotar os torques
plt.figure(figsize=(10, 5))
plt.plot(t, torque_ombro, label="Torque no Ombro")
plt.plot(t, torque_cotovelo, label="Torque no Cotovelo")
plt.xlabel("Tempo (s)")
plt.ylabel("Torque (N·m)")
plt.title("Torque nas Articulações em Função do Tempo")
plt.legend()
plt.grid()
plt.show()



import numpy as np
import matplotlib.pyplot as plt

# Parâmetros dos segmentos e do corpo
massa_braco = 3.0  # kg (massa do braço)
comprimento_braco = 0.35  # m (comprimento do braço)
centro_massa_braco = 0.45  # proporção do comprimento
raio_giro_braco = 0.45 * 0.35 # m

massa_antebraco = 2.5  # kg (massa do antebraço)
comprimento_antebraco = 0.30  # m (comprimento do antebraço)
raio_giro_antebraco = 0.4  # proporção do comprimento

massa_tronco = 0.452
comprimento_tronco = 0.288
raio_giro_braco = 0.35

massa_corpo = 70.0  # kg (massa total do corpo)
distancia_centro_massa_ombro = 0.55  # m (distância do centro de massa ao ombro)
distancia_centro_massa_antebraco = 0.43
distancia_centro_massa_braco = 0.53
g = 9.81  # aceleração gravitacional (m/s²)
AnguloVertical = []

for i in range(len(AnguloAntebraco)):
  AnguloVertical.append(AnguloAntebraco[i] - AnguloOmbro[i])

AnguloAntebraco[:len(t)] = butter_lowpass_filter(AnguloAntebraco[:len(t)], cutoff, fs)


# Função para calcular o torque
def CalculaTorque(massa_segmento, comprimento_segmento, raio_giro, aceleracao_angular, angulo_articular, massa_corpo=0, distancia_centro_massa_corpo=0):
    raio_giro_m = comprimento_segmento * raio_giro
    momento_inercia = massa_segmento * raio_giro_m**2
    componente_inercial = momento_inercia * aceleracao_angular
    componente_gravitacional = massa_corpo * g * distancia_centro_massa_corpo * np.cos(angulo_articular)
    return componente_inercial + componente_gravitacional


# Calcular o torque do cotovelo
raio_giro_m = comprimento_antebraco * raio_giro_antebraco
momento_inercia = massa_antebraco * raio_giro_m**2
componente_inercial = momento_inercia * AA1[:len(t)]


componente_gravitacional1 = (massa_braco) * g * distancia_centro_massa_braco * comprimento_braco * np.sin(AnguloAntebraco[:len(t)])
componente_gravitacional2 = (massa_corpo - (massa_braco+massa_antebraco)) * g * comprimento_braco * np.sin(AnguloAntebraco[:len(t)])
componente_gravitacional = componente_gravitacional1 + componente_gravitacional2

torque_cotovelo = componente_inercial #+ componente_gravitacional


# Calcular o torque no ombro
raio_giro_m = comprimento_tronco * raio_giro_braco * 1.76
momento_inercia = massa_tronco * 70 * raio_giro_m**2
componente_inercial = momento_inercia * AA2[:len(t)]
componente_gravitacional = 70 * massa_tronco * g * distancia_centro_massa_corpo * np.sin(AnguloVertical[:len(t)])
torque_ombro = componente_inercial #+ componente_gravitacional

#torque_cotovelo = butter_lowpass_filter(torque_cotovelo, 4, fs)
# torque_ombro = butter_lowpass_filter(torque_ombro, 7, fs)



# # Calcular o torque no ombro
# torque_ombro = CalculaTorque(
#     massa_segmento=massa_braco,
#     comprimento_segmento=comprimento_braco,
#     raio_giro=raio_giro_braco,
#     aceleracao_angular=AA1,
#     angulo_articular=AnguloOmbro[:len(t)],
#     massa_corpo=massa_corpo,
#     distancia_centro_massa_corpo=distancia_centro_massa_corpo
# )


# Calcular o torque no cotovelo
# torque_cotovelo = CalculaTorque(
#     massa_segmento=massa_antebraco,
#     comprimento_segmento=comprimento_antebraco,
#     raio_giro=raio_giro_antebraco,
#     aceleracao_angular=AA2,
#     angulo_articular= AnguloCotovelo[:len(t)]
# )

# Plotar os torques
plt.figure(figsize=(10, 5))
plt.plot(t, torque_ombro, label="Torque no Ombro")
plt.plot(t, torque_cotovelo, label="Torque no Cotovelo")
plt.xlabel("Tempo (s)")
plt.ylabel("Torque (N·m)")
plt.title("Torque nas Articulações em Função do Tempo")
plt.legend()
plt.grid()
plt.show()

plt.figure(figsize=(8, 5))
plt.plot(t, AnguloAntebraco[:len(t)], label='Ângulo Vertical')
plt.plot(t, AnguloCotovelo[:len(t)], label='Ângulo Horizontal', color='red')

#plt.plot(t, AnguloAntebraco[:len(t)], label='Ângulo Vertical', color='red')

# Configurações do gráfico
plt.title('Ângulo Vertical em Função do Tempo')
plt.xlabel('Tempo (s)')
plt.ylabel('Ângulo Vertical (graus)')
plt.grid(True)
plt.legend()
plt.show()

plt.clf()
sin_values = np.sin(AnguloAntebraco[:len(t)])
plt.plot(t, sin_values, label="sin(Ângulo do Antebraço)")
plt.xlabel("Tempo (s)")
plt.ylabel("sin(Ângulo)")
plt.title("Comportamento de sin(Ângulo do Antebraço)")
plt.legend()
plt.grid()
plt.show()

BracoTriceps = np.mean(BracoAlavancaTriceps)
BracoBiceps = np.mean(BracoAlavancaBiceps)/10

print(BracoTriceps)
print(BracoBiceps)

Forca_Biceps = torque_cotovelo/BracoBiceps
Forca_Triceps = -torque_cotovelo/BracoTriceps

# Plotar os Forças
plt.figure(figsize=(10, 5))
plt.plot(t, Forca_Biceps, label="Força no Bíceps")
plt.plot(t, Forca_Triceps, label="Força no Tríceps")
plt.xlabel("Tempo (s)")
plt.ylabel("Força (N)")
plt.title("Força dos músculos em Função do Tempo")
plt.legend()
plt.grid()
plt.show()

def calcular_torque(forca, comprimento, angulo):
    """
    Calcula o torque.
    Args:
        forca (float): Força aplicada (N).
        comprimento (float): Braço de momento (m).
        angulo (float): Ângulo entre o vetor muscular e a linha de ação da força (rad).
    Returns:
        float: Torque em N·m.
    """
    return comprimento * forca * np.sin(angulo)


torque_cotovelo = []
torque_ombro = []

for i in range(len(t)):
    # Torque no cotovelo
    angulo_cotovelo_rad = np.radians(AnguloCotovelo[i])
    comprimento_biceps = Biceps[i]
    forca_biceps = 50  # Estimativa inicial de força (ajustar conforme o modelo)
    torque_cotovelo.append(calcular_torque(forca_biceps, comprimento_biceps, angulo_cotovelo_rad))

    # Torque no ombro
    angulo_ombro_rad = np.radians(AnguloOmbro[i])
    comprimento_triceps = Triceps[i]
    forca_triceps = 40  # Estimativa inicial de força
    torque_ombro.append(calcular_torque(forca_triceps, comprimento_triceps, angulo_ombro_rad))

# Gráficos de torque
plt.figure(figsize=(12, 6))
plt.plot(t, torque_cotovelo, label="Torque Cotovelo", color="blue")
plt.plot(t, torque_ombro, label="Torque Ombro", color="orange")
plt.xlabel("Tempo (s)")
plt.ylabel("Torque (N·m)")
plt.title("Torque ao Longo do Tempo")
plt.legend()
plt.grid(True)
plt.show()

# Gráficos de força muscular
forca_biceps = [calcular_forca(tc, Biceps[i], np.radians(AnguloCotovelo[i])) for i, tc in enumerate(torque_cotovelo)]
forca_triceps = [calcular_forca(to, Triceps[i], np.radians(AnguloOmbro[i])) for i, to in enumerate(torque_ombro)]

plt.figure(figsize=(12, 6))
plt.plot(t, forca_biceps, label="Força Bíceps", color="green")
plt.plot(t, forca_triceps, label="Força Tríceps", color="red")
plt.xlabel("Tempo (s)")
plt.ylabel("Força Muscular (N)")
plt.title("Força Muscular ao Longo do Tempo")
plt.legend()
plt.grid(True)
plt.show()



massa_corporal = 70 # rever a massa que vamos usar

# Calcular a força muscular com base na aceleração (usando acelerações já calculadas no código)
forca_biceps = [massa_corporal * acc for acc in AceleracaoBiceps]  # Força no bíceps
forca_triceps = [massa_corporal * acc for acc in AceleracaoTriceps]  # Força no tríceps

# Plotar a força muscular ao longo do tempo
plt.figure(figsize=(12, 6))
plt.plot(t, forca_biceps, label="Força Bíceps (N)", color="blue")
plt.plot(t, forca_triceps, label="Força Tríceps (N)", color="red")
plt.xlabel("Tempo (s)")
plt.ylabel("Força (N)")
plt.title("Força Muscular ao Longo do Tempo")
plt.legend()
plt.grid(True)
plt.show()